# Generated by Django 4.2.4 on 2023-08-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260, verbose_name='Команда')),
                ('role', models.CharField(max_length=255, verbose_name='Роль')),
                ('image', models.ImageField(blank=True, default='image.jpg', upload_to='upload/posts', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Участники команды',
            },
        ),
    ]
