# Generated by Django 4.2.4 on 2023-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_end', models.TextField(verbose_name='Фронтенд')),
                ('back_end', models.TextField(verbose_name='бэкенд')),
                ('ux_ui', models.TextField(verbose_name='Дизайн разработчик')),
                ('android', models.TextField(verbose_name='андройд разработчик')),
            ],
            options={
                'verbose_name': 'Курс програмирование',
                'verbose_name_plural': 'Курсы програмирование',
            },
        ),
    ]
