# Generated by Django 4.2.4 on 2023-08-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_benefist_alter_android_options_alter_back_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefist',
            name='image',
            field=models.ImageField(default=1, upload_to=True, verbose_name='Фотография преимущество'),
            preserve_default=False,
        ),
    ]
